(*:Title: OrganDetection *)
(*:Context: OrganDetection` *)
(*:Authors: Giuseppe Spathis, ... da sistemare *)
(*:Summary: Organ detection based on ultrasound images using deep learning algorithms, implemented in Wolfram Mathematica. *)
(*:Copyright: GS 2025 da sistemare *)
(*:Package Version: 1 *)
(*:Mathematica Version: 14 ...da vedere *)
(*:History: last modified 14/3/2025 ... da sistemare *)
(*:Keywords: Organ detection, ultrasound images *)
(*:Sources: biblio *)
(*:Limitations: this is for educational purposes only. *)
(*:Discussion: *)
(*:Requirements: *)
(*:Warning: package Context is not defined *)